quizprj/quizapp/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    
    path('home/', views.home, name='home'),
    path('user-home/', views.user_home, name='user_home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    
    path('start/', views.start, name='start'),
    
    path('dashboard/', views.dashboard, name='dashboard'),
    
    path('question/', views.add_question, name='add_question'),
    
    path('addChoice/<int:p_id>/', views.add_choice, name='addChoice'),
    # path('editchoice/<int:choice_id>/', views.choice_edit, name='editchoice'),
    # path('choicedelete/<int:choice_id>/',views.choice_delete, name='choicedelete'),
    
    path('edit/<int:p_id>/', views. edit_question, name='editQuestion'),
    # path('delete/<int:p_id>/', views.polls_delete, name='deleteQuestion'),
    
    path('submission-result/<int:attempted_question_pk>/', views.submission_result, name='submission_result'),
    
    
    path('timer/', views.timer, name='timer'),
    
    
    
    
]

quizprj/quizprj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizapp.urls'))
]

quizprj/quizapp/models.py
import random
from django.db import models
from django.db.models import F, Q, Count, Sum, Case, When
from django.db.models.functions import Cast
from django.contrib.auth.models import User
from django.utils.translation import gettext as _


class Question(models.Model):
    ALLOWED_NUMBER_OF_CORRECT_CHOICES = 1

    qus_txt = models.TextField(_('Question Text'))
    is_published = models.BooleanField(_('Has been published?'), default=False, null=False)
    maximum_marks = models.DecimalField(_('Maximum Marks'), default=4, decimal_places=2, max_digits=6)


    def __str__(self):
        return self.qus_txt


class Choice(models.Model):
    MAX_CHOICES_COUNT = 4

    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(_('Is this answer correct?'), default=False, null=False)
    choice_text = models.TextField(_('Choice Text'))
    

    def __str__(self):
        return self.choice_text


class QuizProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_score = models.DecimalField(_('Total Score'), default=0, decimal_places=2, max_digits=10)

    def __str__(self):
        return f'<QuizProfile: user={self.user}>'
    def get_new_question(self):
        
        used_questions_pk = AttemptedQuestion.objects.filter(quiz_profile=self).values_list('question__pk', flat=True)
        
        remaining_questions = Question.objects.exclude(pk__in=used_questions_pk)
        
        
        if not remaining_questions.exists():
            return
        return random.choice(remaining_questions)

    def create_attempt(self, question):
        attempted_question = AttemptedQuestion(question=question, quiz_profile=self)
        attempted_question.save()

    def evaluate_attempt(self, attempted_question, selected_choice):
        if attempted_question.question_id != selected_choice.question_id:
            return

        attempted_question.selected_choice = selected_choice
        if selected_choice.is_correct is True:
            attempted_question.is_correct = True
            attempted_question.marks_obtained = attempted_question.question.maximum_marks

        attempted_question.save()
        self.update_score()
        
    @classmethod
    def get_rankings(cls):
        rankings = QuizProfile.objects.select_related(
            'user',
        ).annotate(
            total_attempts=Count('attempts'),
            correct_attempts=Sum(Case(When(attempts__is_correct=True, then=1), default=0, output_field=models.IntegerField())),
            success_rate=Cast(100.0 * F('correct_attempts') / F('total_attempts'), models.FloatField())
        ).order_by(
            '-total_score',
            '-correct_attempts',
            '-success_rate'
        )
        return rankings

    def update_score(self):
        marks_sum = self.attempts.filter(is_correct=True).aggregate(
            models.Sum('marks_obtained'))['marks_obtained__sum']
        self.total_score = marks_sum or 0
        self.save()


class AttemptedQuestion(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    quiz_profile = models.ForeignKey(QuizProfile, on_delete=models.CASCADE, related_name='attempts')
    selected_choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True)
    is_correct = models.BooleanField(_('Was this attempt correct?'), default=False, null=False)
    marks_obtained = models.DecimalField(_('Marks Obtained'), default=0, decimal_places=2, max_digits=6)

quizprj/templates/quiz/add_choice.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if edit_choice %}
            <h2>Update choice</h2>
            {% else %}
            <h2>Add new choice</h2>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                {% if edit_choice %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'quiz:choicedelete' choice.id %}" role="button" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                {% else %}
                <button type="submit" class="btn btn-primary">Add</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

quizprj/templates/quiz/create_question.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    {% if user.is_authenticated and user.is_staff %}
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Create Question poll</h2>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                <input type="hidden" name="question_pk" value="{{ question.pk }}">
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Add Question</button>
                <a class="btn btn-warning" href="{% url 'quiz:home' %}" role="button">Back</a>
            </form>
        </div>
    </div>
    {% else %}
        <h1>Error: Unauthorized Access</h1>
        <p>You are not authorized to access this page.</p>
    {% endif %}
    
</div>
{% endblock %}

quizprj/templates/quiz/dashboard.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="text-center my-4"><span class="badge badge-primary"><i class="fa fa-trophy" aria-hidden="true"></i> TOP {{ total_count }} PLAYERS <i class="fa fa-trophy" aria-hidden="true"></i></span></h1>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Position</th>
                <th>Username</th>
                <th>Score</th>
                <th>Total Attempts</th>
                <th>Correct Attempts</th>
                <th>Success rate</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz_profile in top_quiz_profiles %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ quiz_profile.user.username }}</td>
                <td>{{ quiz_profile.total_score }}</td>
                <td>{{ quiz_profile.total_attempts }}</td>
                <td>{{ quiz_profile.correct_attempts }}</td>
                <td>{{ quiz_profile.success_rate|floatformat:2 }}%</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

quizprj/templates/quiz/edit_question.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Edit Question</h2>
            {% if messages %}
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Update</button>
                
                <a class="btn btn-warning" href="{% url 'quiz:addChoice' poll.id %}" role="button">Add Choice</a>
            </form>

            <!-- <div class="choices">
                <h2 class="text-center mt-3">Choices</h2>
                <hr>
                <ul class="list-group">
                    {% for choice in poll.choice_set.all %}
                    <li class="list-group-item"><a href="{% url 'quiz:editchoice' choice.id %}"><i class="fas fa-pencil-alt"></i></a>&nbsp
                        {{ choice.choice_text }}</li>
                    {% endfor %}
                </ul>
            </div>  -->

        </div>
    </div>
</div>
{% endblock %}

quizprj/templates/quiz/home.html
{% extends 'base.html' %}
{% block title %} Quiz Application | Home {% endblock title %}
{% block content %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-primary">Quiz Application</h1>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
        <p class="lead">We organize quizzes on various topics.</p>

        {% if not request.user.is_active %}

        <p class="lead">Sign up if you haven't already and get access to millions of quizzes on the topic of your interest.</p>
        <p><strong> Start Your Journey Here:</strong></p>
        <a href="{% url 'quiz:register' %}" class="btn btn-lg btn-info mt-1"><i class="fa fa-user-plus" aria-hidden="true"></i> Sign Up</a>

        {% else %}
        <a href="{% url 'quiz:start' %}" class="btn btn-lg btn-info mt-1">Let's start quiz</a>
        <a href="{% url 'quiz:dashboard' %}" class="btn btn-lg btn-info mt-1">Dashboard</a>
        {% endif %}
      </div>
    </section>

{% endblock content %}

quizprj/templates/quiz/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Quiz Application | {{ title }} {% endblock title %}
{% block content %}
{% if not request.user.is_active %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
              <h1 class="mb-3 text-center">Please log in</h1>
                <form method="POST" action="">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" class="btn btn-info btn-block" value="{{ title }}"> 
                </form>
              <div class="text-center">
                <p>or ...</p>
                <a href="{% url 'quiz:register' %}" class="btn btn-success mb-3">Create account</a>
              </div>
            </div>
          </div>
        </div>
      </div>
{% else %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-info">Quiz Application</h1>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
        <p class="lead">We organize quizzes on various topics.</p>
        <a href="{% url 'quiz:start' %}" class="btn btn-lg btn-info mt-1">Let's start quiz</a>
        <a href="{% url 'quiz:dashboard' %}" class="btn btn-lg btn-info mt-1">Dashboard</a>
      </div>  
    </section>

{% endif %}

{% endblock content %}

quizprj/templates/quiz/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Quiz Application| {{ title }} {% endblock title %}
{% block content %}
     <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
              <h1 class="mb-3 text-center">Create a new account</h1>
              <form class="mb-3" method="POST" action="">
                {% csrf_token %}
		            {{form|crispy}}
		        <input type="submit" class="btn btn-info btn-block mb-3" value="{{ title }}"> 
              </form>
              <div class="text-center">
                <p>or ...</p>
                <a href="{% url 'quiz:login' %}" class="btn btn-success">Login</a>
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock content %}

quizprj/templates/quiz/start copy.html
{% extends 'base.html' %}

{% block content %}

{% if question is None %}
<div class="container">
  <div class="jumbotron my-4">
    <h1> You have already answered all of our questions. </h1>
    <a href="{% url 'quiz:dashboard' %}" class="btn btn-lg btn-info"><i class="fa fa-trophy" aria-hidden="true"></i> See the leaderboard here <i class="fa fa-trophy" aria-hidden="true"></i></a>
  </div>
</div>

{% else %}

<div class="container">
  {% if messages %}
  <div class="messages">
      {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
      {% endfor %}
  </div>
  {% endif %}
  <hr>
  <div align="right " id="displaytimer"><b>Timer: 0 seconds</b></div>
  <h2 class="mt-3 mb-3">{{ question }}</h2>
  <form action="" method="POST">
      {% csrf_token %}
      <input type="hidden" name="question_pk" value="{{ question.pk }}">
      {% for choice in question.choices.all %}
      <input type="radio" name="choice_pk" id="choice{{ forloop.counter }}" value="{{ choice.pk }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
      <br>
      {% endfor %}
      <input id='timer' type='hidden' name="timer" value="">
      <br>
      <!-- <input type="submit" value="Submit" class="btn btn-primary mt-3"> -->
      <input class="btn btn-info btn-lg" type="submit" value="Submit">  
      <a class="btn btn-warning mt-3" href="{% url 'quiz:home' %}" role="button">Cancel</a>
  </form>

  {% block script %}
    <script>
        console.log('hello...')
        const timer=document.getElementById('displaytimer')
        console.log(timer.textContent)
        const inputtag = document.getElementById('timer')

        t=0
        setInterval(()=>{
            t+=1
            timer.innerHTML ="<b>Timer: " +t+" seconds</b>"
            inputtag.value = t
        },1000)
    </script>
{% endblock script %}

</div>
{% endif %} 



{% endblock content %}

quizprj/templates/quiz/start.html
{% extends 'base.html' %}
{% include "quiz/timer.html" %}
{% block content %}

{% if question is None %}
<div class="container">
  <div class="jumbotron my-4">
    <h1> You have already answered all of our questions. </h1>
    <a href="{% url 'quiz:dashboard' %}" class="btn btn-lg btn-info"><i class="fa fa-trophy" aria-hidden="true"></i> See the leaderboard here <i class="fa fa-trophy" aria-hidden="true"></i></a>
  </div>
</div>

{% else %}

<div class="container">
  <hr>

  <script type="text/javascript">
    window.onload = function begin(){
    document.getElementById('timer').innerHTML =
      2 + ":" + 00;
    startTimer();
    }
    
    function startTimer() {
      var presentTime = document.getElementById('timer').innerHTML;
      var timeArray = presentTime.split(/[:]+/);
      var m = timeArray[0];
      var s = checkSecond((timeArray[1] - 1));
      if(s==59){m=m-1}
      if(m<0){
        document.getElementById('quiz').submit();
        //document.getElementById("submitBtn").click();
      }
      document.getElementById('timer').innerHTML =
        m + ":" + s;
      setTimeout(startTimer, 1000);
    }
    
    function checkSecond(sec) {
      if (sec < 10 && sec >= 0) {sec = "0" + sec}; // add zero in front of numbers < 10
      if (sec < 0) {sec = "59"};
      return sec;
    }


    </script>

        <div class='float-right sticky-top'>
            <div class="row justify-content-left">
                <div class="col-mx-auto">
                  <div class="alert alert-success" role="alert"><center>Time left : <span id="timer"></span></center></div>
                </div>
            </div>
        </div>


  <div class="mt-3 mb-3 h4">{{ question }}</div>
  <div>
  <form id="quiz" action="" method="POST" >
      {% csrf_token %}
      <input type="hidden" name="question_pk" value="{{ question.pk }}">
      {% for choice in question.choices.all %}
      <input type="radio" name="choice_pk" id="choice{{ forloop.counter }}" value="{{ choice.pk }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text  }}</label>
      <br>
      {% endfor %}
      <!-- <input id='timer' type='hidden' name="timer" value=""> -->
      <br>
      <input type="submit" id="submitBtn" value="Submit" class="btn btn-primary mt-3">
      <!-- <input class="btn btn-info btn-lg" type="submit" value="Submit">   -->
      <a class="btn btn-warning mt-3" href="{% url 'quiz:home' %}" role="button">Cancel</a>
  </form>
  </div>

{% endif %} 

{% endblock content %}

</div>

quizprj/templates/quiz/submission_result.html
{% extends 'base.html' %}
{% block title %} Quiz Application | Submission Result {% endblock title %}
{% block content %}
<div class="container">
	<div class="jumbotron my-4">

	   	<h3 class="text-info">{{ attempted_question.question.html|safe }}</h3>

		<p>
		    <strong>Your answer: </strong>
		    {{ attempted_question.selected_choice.html|safe }}
		</p>

		{% if attempted_question.selected_choice.is_correct %}
		<h4 class="text-success">Yayy!! Your answer is correct. High Five! 🙌</h4>
		{% else %}
		<h4 class="text-danger">Your answer is incorrect 😟</h4>
		{% endif %}

		<a class="btn btn-info" href="{% url 'quiz:start' %}">Show next question</a>
	</div>
</div>

{% endblock content %}

quizprj/templates/quiz/timer.html
<!DOCTYPE html>
<html>
<h1> timer page</h1>
<body>
    
</html>

<script type="text/javascript">
    window.onload = function begin(){
    document.getElementById('timer').innerHTML =
      30 + ":" + 00;
    startTimer();
    }
    
    function startTimer() {
      var presentTime = document.getElementById('timer').innerHTML;
      var timeArray = presentTime.split(/[:]+/);
      var m = timeArray[0];
      var s = checkSecond((timeArray[1] - 1));
      if(s==59){m=m-1}
      if(m<0){
        document.getElementById('quiz').submit();
      }
      document.getElementById('timer').innerHTML =
        m + ":" + s;
      setTimeout(startTimer, 1000);
    }
    
    function checkSecond(sec) {
      if (sec < 10 && sec >= 0) {sec = "0" + sec}; // add zero in front of numbers < 10
      if (sec < 0) {sec = "59"};
      return sec;
    }
    </script>




    <script type="text/javascript">
        window.onload = function begin(){
        document.getElementById('timer').innerHTML =
          30 + ":" + 00;
        startTimer();
        }
        
        function startTimer() {
          var presentTime = document.getElementById('timer').innerHTML;
          var timeArray = presentTime.split(/[:]+/);
          var m = timeArray[0];
          var s = checkSecond((timeArray[1] - 1));
          if(s==59){m=m-1}
          if(m<0){
            document.getElementById('quiz').submit();
          }
          document.getElementById('timer').innerHTML =
            m + ":" + s;
          setTimeout(startTimer, 1000);
        }
        
        function checkSecond(sec) {
          if (sec < 10 && sec >= 0) {sec = "0" + sec}; // add zero in front of numbers < 10
          if (sec < 0) {sec = "59"};
          return sec;
        }
        </script>

        
        <div class='float-right sticky-top'>
            <div class="row justify-content-left">
                <div class="col-mx-auto">
                    <div class="alert alert-success" role="alert"><center>Time left : <span id="timer"></span></center></div>
                </div>
            </div>
        </div>

    </body>

quizprj/templates/quiz/timer_one.html
<!DOCTYPE html>
<html>
<h1> timer page</h1>
<body>
<div class="game_info" data-spy="scroll" data-target=".header">

    <div class="col-md-6 col-sm-6 col-xs-12">
       <div class="row">
            <div class="full">
                
                    <div class="right-match-time">
                        <h2>Next Match</h2>
                        <h3>....{{ques.date}}</h3>
                        <ul id="countdown-1" class="countdown">
                        <li><span id="days"></span>Day </li>
                        <li><span id="hours"></span>Hours </li>
                        <li><span id="minutes"></span>Minutes </li>
                        <li><span id="seconds"></span>Seconds </li>
                        </ul>
                
                    </div>
            </div>
       </div>
    </div>
</div>
</body>
</html>
<script>
    function makeTimer() {
        var selected_date = new Date("{{ ques.date.isoformat }}");
        var endTime=new Date("{{ques.date|date:'U'}}" * 1000);
        consol.log('========----------=============',selected_date)
        consol.log('==========###########================',endTime)
        endTime = (Date.parse(endTime) / 1000);
    
            var now = new Date();
            now = (Date.parse(now) / 1000);
    
            var timeLeft = endTime - now;
    
            var days = Math.floor(timeLeft / 86400);
            var hours = Math.floor((timeLeft - (days * 86400)) / 3600);
            var minutes = Math.floor((timeLeft - (days * 86400) - (hours * 3600 )) / 60);
            var seconds = Math.floor((timeLeft - (days * 86400) - (hours * 3600) - (minutes * 60)));
    
            if (hours < "10") { hours = "0" + hours; }
            if (minutes < "10") { minutes = "0" + minutes; }
            if (seconds < "10") { seconds = "0" + seconds; }
    
            $("#days").html(days + "<span>Days</span>");
            $("#hours").html(hours + "<span>Hours</span>");
            $("#minutes").html(minutes + "<span>Minutes</span>");
            $("#seconds").html(seconds + "<span>Seconds</span>");
    
    }
    setInterval(function() { makeTimer(); }, 1000);
</script>

quizprj/templates/quiz/user_home.html
{% extends 'base.html' %}

{% block title %} Quiz Application | Welcome {% endblock title %}

{% block content %}
<div class="conatainer my-4">
    {% if user.is_authenticated and user.is_staff %}
    <div class="Jambotraon">
        <h2 class="text-center text-info">Congratulations!! You have successfully logged in as Admin.</h2>
        <h3 class="text-info text-center">add Question click on below button .</h3>
        <div class="d-flex justify-content-center h1">
            <a href="{% url 'quiz:add_question' %}" class="btn btn-primary">Add Question</a>
        </div>
    </div>
    {% else %}
    <div class="Jambotraon">
        <h2 class="text-center text-info">Congratulations!! You have successfully logged in.</h2>
        <h3 class="text-info text-center">Before you start the quiz, here are the rules</h3>
    </div>
    <div class="row">
        <div class="card border info mx-4 my-4" >

            <div class="card-body text-info">
                <h4 class="title">Rules: </h4>
                <p>
                    <ul style="list-style:decimal;">
                        <li>All questions are multiple choice question.</li>
                        <li><span class="text-danger">Only one choice is correct.</span></li>
                        <li>Every question carry equal marks i.e. <span class="text-danger">4 marks for each question.</span>
                        </li>
                        <li>Every question is displayed only once per user.</li>
                        <li>Try to answer as quickly as you can.</li>
                        <li>If you press refresh or go back to the previous page, there will be a new question for you and the question you were on will be counted as attempted.</li>
                        <li>Questions are displayed randomly for every user.</li>
                        <li>You will be told immediately whether your answer was correct or incorrect once you submit the answer.</li>
                    </ul>
                </p> 
                    <a href="{% url 'quiz:start' %}" class="btn btn-info"> Start Quiz </a>
            </div>
        </div>

        <div class="card-footer">Rules last modified 23-june-2023</div>

    </div>

    {% endif %}

</div>
{% endblock content%}